apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "applicationName" . }}
data:
  {{- if .Values.config }}
  {{- range $index, $value := .Values.config -}}
    {{- if $value -}}
      {{- $index | upper | nindent 2 }}: {{ tpl ($value | quote) $ }}
    {{- end -}}
  {{- end -}}
{{- end }}
