apiVersion: v1
kind: Secret
metadata:
  name: {{ include "applicationName" . }}
type: Opaque
stringData:
  {{- if .Values.secrets }}
  {{- range $index, $value := .Values.secrets -}}
    {{- if $value -}}
      {{- $index | upper | nindent 2 }}: {{ tpl ($value | quote) $ }}
    {{- end -}}
  {{- end -}}
{{- end }}
