apiVersion: v1
kind: Service
metadata:
  name: {{ include "applicationName" . }}
  labels:
    app: {{ include "applicationName" . }}
    service: {{ include "applicationName" . }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: {{ .Values.deployment.containerPort }}
  selector:
    app: {{ include "applicationName" . }}