{{ if .Values.mesh.canary.alternateVirtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "applicationName" . }}-canary-external-virtual-service
spec:
  hosts:
{{ tpl (toYaml .Values.mesh.canary.alternateVirtualService.hosts) . | trim | indent 2 }}
{{- range $index, $value := .Values.mesh.canary.alternateVirtualService.redirects.authority  }}
  - {{ tpl $value.fromHost $ }}
{{- end }}
  gateways:
{{ tpl (toYaml .Values.mesh.canary.alternateVirtualService.gateways) . | trim | indent 2 }}
  http:
{{- range $index, $value := .Values.mesh.canary.alternateVirtualService.redirects.authority }}
  - match:
    - authority:
        exact: {{ tpl $value.fromHost $ }}
    redirect:
      authority: {{ tpl $value.toHost $ }}
      {{ if $value.toUri }}
      uri: {{ tpl $value.toUri $ }}
      {{ end }}
{{- end }}
  - name: primary
    match:
    - uri:
        prefix: {{ tpl .Values.mesh.matchPath . }}
    route:
    - destination:
        host: {{ include "applicationName" . }}
        subset: canary
        port:
          number: 80
      weight: 100
    corsPolicy:
{{ tpl (toYaml .Values.mesh.canary.alternateVirtualService.corsPolicy) . | indent 6 }}
{{ end }}
