#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

# Reference: https://github.com/git/git/blob/main/templates/hooks--pre-push.sample

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

IFS=' '
while read local_ref local_sha remote_ref remote_sha
do
  # Handle delete by not running any tests
  [ "$local_sha" = $z40 ] && exit 0

  if [ "$remote_sha" = $z40 ]; then
    # New branch, test against develop
    commit="origin/develop"
  else
    # Update to existing branch, test against remote
    commit=$remote_sha
  fi

  echo "npx tsc && CI=true npm run test -- --changedSince $commit"
  npx tsc && CI=true npm run test -- --changedSince $commit
done
